#!/usr/bin/env python3
"""Clone the pinned Omarchy bar into user config and add phone safe insets."""
import hashlib
import json
from pathlib import Path
import shutil

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT.parent / 'fire-hd8-omarchy/working/desktop/rootfs/usr/share/omarchy/shell/plugins/bar'
OUT = ROOT / 'port/vegas/root/home/omarchy/.config/omarchy/plugins/vegas-bar'
EXPECTED = {
    'Bar.qml': 'a4d1a8371541bec810fadbbbb51e6330baade451fcc134c9967e5220ab7e8625',
    'BarModel.js': '908f30edce60dcba46d2039ba3d501fd0faa35fa1f90b7dbda69439288f8a8d0',
}


def replace_once(text, before, after):
    if text.count(before) != 1:
        raise RuntimeError('Pinned bar does not match the phone patch')
    return text.replace(before, after, 1)


def main():
    for name, digest in EXPECTED.items():
        if hashlib.sha256((BASE / name).read_bytes()).hexdigest() != digest:
            raise SystemExit(f'Pinned Omarchy bar changed: {name}')
    text = (BASE / 'Bar.qml').read_text()
    # Custom bars are configured in Loader.onLoaded; required properties
    # prevent construction before that injection can happen.
    for before, after in [
        ('required property string omarchyPath', 'property string omarchyPath: Quickshell.env("OMARCHY_PATH")'),
        ('required property var barWidgetRegistry', 'property var barWidgetRegistry: null'),
        ('required property var barConfig', 'property var barConfig: ({})'),
    ]:
        text = replace_once(text, before, after)
    text = replace_once(text,
        '  readonly property int barSize: vertical ? Style.bar.sizeVertical : Style.bar.sizeHorizontal',
        '''  // Initial conservative insets, pending a physical phone fit check.
  // Values are logical pixels; the native portrait session uses scale 1.5.
  function phoneMetric(key, fallback, maximum) {
    var value = root.barConfig ? root.barConfig[key] : undefined
    var number = Number(value)
    return value !== undefined && isFinite(number) && number >= 0 && number <= maximum
      ? Math.round(number) : fallback
  }
  readonly property int phoneSafeTop: phoneMetric("phoneSafeTop", 56, 128)
  readonly property int phoneSideInset: phoneMetric("phoneSideInset", 20, 64)
  readonly property int barSize: vertical ? Style.bar.sizeVertical : Math.max(Style.bar.sizeHorizontal, phoneMetric("phoneBarHeight", 48, 96))''')
    text = replace_once(text,
        '      top: root.barHidden && root.position === "top" ? -root.barSize : 0',
        '      top: root.position === "top" ? (root.barHidden ? -root.barSize : root.phoneSafeTop) : 0')
    for side in ['left', 'right']:
        text = replace_once(text,
            f'      {side}: root.barHidden && root.position === "{side}" ? -root.barSize : 0',
            f'      {side}: !root.vertical ? root.phoneSideInset : (root.barHidden && root.position === "{side}" ? -root.barSize : 0)')
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / 'Bar.qml').write_text(text)
    shutil.copy2(BASE / 'BarModel.js', OUT / 'BarModel.js')
    manifest = json.loads((BASE / 'manifest.json').read_text())
    manifest.update(id='vegas.bar', name='Phone Bar', author='Omarchy; Vegas phone overrides',
                    description='Omarchy bar inset below the phone camera and rounded corners')
    manifest['omarchy'] = {'clonedFrom': 'omarchy.bar'}
    (OUT / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    (OUT / 'README.md').write_text(
        'User-owned clone of the pinned Omarchy ARM bar; packaged source is unchanged.\n'
        'Generated by scripts/prepare-vegas-phone-bar.py. Geometry overrides are\n'
        'phoneSafeTop, phoneSideInset and phoneBarHeight in shell.json bar config.\n'
        'Base file hashes are pinned in that script. Hardware fit check pending.\n')
    print('Prepared user-owned phone bar with top and side safe areas; hardware validation pending.')


if __name__ == '__main__':
    main()
